### PR TITLE
Fix illegal characters in filenames when saving txt

### LINKED ISSUE #46: Fix illegal characters in text file names
Illegal characters should be removed from the suggested file name when saving the text file, as the OS may prevent the user from saving the file otherwise.

### PR DESCRIPTION
**Pull request by DeinAlptraum**
This fixes #46

### CODE REVIEW

File: src/QUMainWindow.cpp [hunk 1]
```diff
@@ -31,6 +31,12 @@
 #include "compact_lang_det.h"
 #include "srtparser.h"
 
+std::vector<std::pair<std::string, const char *>> FILENAME_REPLACEMENTS{
+	std::make_pair(std::string("?:\""), ""),
+	std::make_pair(std::string("<"), "("),
+	std::make_pair(std::string(">"), ")"),
+	std::make_pair(std::string("/\\|*"), "-")};
+
```
Comment (DeinAlptraum) [inline src/QUMainWindow.cpp:39]: Wasn't sure where to put a constant like this one @bohning , would you prefer this in a different place?

Comment (bohning) [reply src/QUMainWindow.cpp:39]: I guess it's fine where it is. The whole Creator code could benefit from some refactoring and splitting into multiple files, but for the status now, I think it's okay to put it right there.

**Review by bohning — APPROVED** [review]
